import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import StyledComponentsRegistry from '../lib/registry';
import { Providers } from './providers';
import StyledProvider from 'src/lib/theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <StyledProvider>
            <Providers>{children}</Providers>
          </StyledProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
